"use client";
import { useRef,useState } from 'react';
import Link from 'next/link';
import { Sparkles, ArrowUpRight, FileText, Save } from 'lucide-react';
import { api } from '@/logaxp/lib/api/apiClient';
import { showcaseAdminService } from '@/logaxp/lib/showcase/showcase.service';
export default function ArticleEditor(){
 const [brief,setBrief]=useState('');const [title,setTitle]=useState('');const [summary,setSummary]=useState('');const [body,setBody]=useState('');const [image,setImage]=useState('/images/4.png');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const lock=useRef(false);
 async function generate(){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{const {data}=await api.post('/admin/articles/draft',{brief},{timeout:65000});setTitle(data.title);setSummary(data.summary);setBody(data.body);setNotice('Draft generated. Review facts and wording before saving.');}catch{setNotice('AI drafting is unavailable. Your work is preserved; check configuration or continue manually.');}finally{lock.current=false;setBusy(false);}}
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{const categories=await showcaseAdminService.listCategories();const category=categories.find(c=>c.slug==='articles')??await showcaseAdminService.createCategory({title:'Articles',slug:'articles'});await showcaseAdminService.create({title,shortDescription:summary,description:body,heroUrl:image,categoryIds:[category.id]});setNotice('Saved as a draft. Open publishing to review and publish it.');setTitle('');setSummary('');setBody('');}catch{setNotice('Could not save the draft. Your text is still here.');}finally{lock.current=false;setBusy(false);}}
 const input='mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 text-slate-950';
 return <div className="space-y-6">
 <div className="admin-page-heading flex flex-wrap items-end justify-between gap-4"><div><div className="admin-kicker">Website / Editorial</div><h1>Article studio</h1><p className="mt-2 text-sm text-slate-500">Turn your expertise into something worth reading.</p></div><Link href="/site-admin/showcases" className="flex items-center gap-2 text-sm font-medium">Manage publishing <ArrowUpRight size={15}/></Link></div>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_280px]">
 <section className="admin-draft-editor space-y-5 rounded-xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/5">
 <div className="flex items-center gap-2 border-b border-slate-100 pb-4 text-sm font-semibold"><FileText size={17}/> Your draft <span className="ml-auto text-xs font-normal text-slate-400">Unpublished</span></div>
 <label className="block text-xs font-medium">Title<input className={input} maxLength={180} value={title} placeholder="Give your article a clear title" onChange={e=>setTitle(e.target.value)}/></label>
 <label className="block text-xs font-medium">Summary<textarea className={input} maxLength={320} value={summary} placeholder="A short introduction for the article card" onChange={e=>setSummary(e.target.value)}/></label>
 <label className="block text-xs font-medium">Article text<textarea className={input+' min-h-80'} value={body} placeholder="Start writing here…" onChange={e=>setBody(e.target.value)}/></label>
 <label className="block text-xs font-medium">Cover image<select className={input} value={image} onChange={e=>setImage(e.target.value)}>{[4,5,6,7].map(n=><option key={n} value={'/images/'+n+'.png'}>Blog collection — image {n-3}</option>)}</select></label>
 {notice&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}
 <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><p className="text-xs text-slate-500">Save a draft, then review it in Publishing.</p><button disabled={busy||title.trim().length<3||body.trim().length<50} onClick={save} className="flex items-center gap-2 rounded-lg bg-[#203c2e] px-4 py-2 text-sm font-medium text-white disabled:opacity-50"><Save size={15}/>Save draft</button></div>
 </section>
 <aside className="space-y-4"><section className="rounded-xl border border-[#dce6d2] bg-[#f0f5e9] p-5 text-[#28402d]"><Sparkles size={22}/><h2 className="mt-4 text-base font-semibold">A little help getting started</h2><p className="mt-2 text-xs leading-5">Give AI a topic, an audience and the facts you want to share. You stay in control of the final words.</p><label className="mt-4 block text-xs font-medium">Your brief<textarea className={input+' min-h-36'} maxLength={4000} value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Topic, audience and verified facts…"/></label><button disabled={busy||brief.trim().length<20} onClick={generate} className="mt-3 w-full rounded-lg bg-[#203c2e] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy?'Working…':'Generate first draft'}</button><p className="mt-3 text-[11px] leading-5">Your brief is sent to OpenAI. Leave out private customer or employee information, and check every claim before publishing.</p></section><Link href="/blog" className="flex items-center justify-between rounded-lg border border-slate-200 bg-white p-4 text-xs dark:bg-white/5">View public articles <ArrowUpRight size={15}/></Link></aside>
 </div></div>;
}
