"use client";
import { useRef,useState } from 'react';
import Link from 'next/link';
import { api } from '@/logaxp/lib/api/apiClient';
import { showcaseAdminService } from '@/logaxp/lib/showcase/showcase.service';
export default function ArticleEditor(){
 const [brief,setBrief]=useState('');const [title,setTitle]=useState('');const [summary,setSummary]=useState('');const [body,setBody]=useState('');const [image,setImage]=useState('/images/4.png');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const lock=useRef(false);
 async function generate(){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{const {data}=await api.post('/admin/articles/draft',{brief},{timeout:65000});setTitle(data.title);setSummary(data.summary);setBody(data.body);setNotice('Draft generated. Review facts and wording before saving.');}catch{setNotice('AI drafting is unavailable. Your work is preserved; check configuration or continue manually.');}finally{lock.current=false;setBusy(false);}}
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{const categories=await showcaseAdminService.listCategories();const category=categories.find(c=>c.slug==='articles')??await showcaseAdminService.createCategory({title:'Articles',slug:'articles'});await showcaseAdminService.create({title,shortDescription:summary,description:body,heroUrl:image,categoryIds:[category.id]});setNotice('Saved as a draft. Open publishing to review and publish it.');setTitle('');setSummary('');setBody('');}catch{setNotice('Could not save the draft. Your text is still here.');}finally{lock.current=false;setBusy(false);}}
 const input='mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 text-slate-950';
 return <div className="mx-auto max-w-4xl space-y-6"><h1 className="text-3xl font-bold">Articles</h1><p>Write an article or use AI to prepare a first draft. Only the brief you enter is sent to OpenAI. Do not include private employee or customer information. Review every claim before publishing.</p><div className="flex flex-wrap gap-4"><Link href="/site-admin/showcases" className="underline">Manage drafts and publishing</Link><Link href="/blog" className="underline">View public articles</Link><Link href="/site-admin/enquiries" className="underline">Sales inbox</Link></div><label className="block">Article brief<textarea className={input} maxLength={4000} value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Topic, audience and verified facts…"/></label><button disabled={busy||brief.trim().length<20} onClick={generate} className="rounded-lg bg-slate-900 px-5 py-3 text-white disabled:opacity-50">{busy?'Working…':'Generate AI draft'}</button>{notice&&<p role="status" className="rounded border p-4">{notice}</p>}<label className="block">Title<input className={input} maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block">Summary<textarea className={input} maxLength={320} value={summary} onChange={e=>setSummary(e.target.value)}/></label><label className="block">Article text<textarea className={`${input} min-h-80`} value={body} onChange={e=>setBody(e.target.value)}/></label><label className="block">Existing cover image<select className={input} value={image} onChange={e=>setImage(e.target.value)}>{[4,5,6,7].map(n=><option key={n} value={`/images/${n}.png`}>Original blog image {n-3}</option>)}</select></label><button disabled={busy||title.trim().length<3||body.trim().length<50} onClick={save} className="rounded-lg bg-[#86BF00] px-5 py-3 font-bold text-black disabled:opacity-50">Save draft for review</button></div>;
}
